# Gabriel Ramos Xavier de Souza
### Teste: Buscar todos os clientes
GET http://127.0.0.1:8000/cliente/
Accept: application/json

### Teste: Buscar um cliente por ID
GET http://127.0.0.1:8000/cliente/1
Accept: application/json

### Teste: Criar um novo cliente
POST http://127.0.0.1:8000/cliente/
Content-Type: application/json

{
  "id_cliente": 1,
  "nome": "João da Silva",
  "cpf": "123.456.789-00",
  "telefone": "(11) 98765-4321"
}

### Teste: Atualizar um cliente existente
PUT http://127.0.0.1:8000/cliente/1
Content-Type: application/json

{
  "id_cliente": 1,
  "nome": "Gabriel Ramos Xavier de Souza",
  "cpf": "123.456.789-00",
  "telefone": "(11) 99999-8888"
}

### Teste: Deletar um cliente pelo ID
DELETE http://127.0.0.1:8000/cliente/1
Accept: application/json
